# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dist: trusty

language: c

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y --force-yes gcc-arm-none-eabi

before_script:
  - arm-none-eabi-gcc --version

script:
  - make && make test
